// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout"; // Import ClientLayout
import { ClerkProvider } from '@clerk/nextjs';
import { shadesOfPurple } from '@clerk/themes'
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata: Metadata = {
  title: "Avion",
  description: "Generated by Muhammad Abdullah Khan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: [shadesOfPurple],
        variables: { colorPrimary: 'white' },
      signIn: {
        baseTheme: [shadesOfPurple],
        variables: { colorPrimary: 'white' },
      },
    }}>
    <html lang="en" suppressHydrationWarning>
      <body>
        
        <ClientLayout>{children} <SpeedInsights /></ClientLayout> {/* Wrap children with ClientLayout */}
      </body>
    </html>
    </ClerkProvider>
  );
}
