// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout"; // Import ClientLayout
import { ClerkProvider } from '@clerk/nextjs';
import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: [shadesOfPurple],
        variables: { colorPrimary: 'white' },
      signIn: {
        baseTheme: [shadesOfPurple],
        variables: { colorPrimary: 'white' },
      },
    }}>
    <html lang="en" suppressHydrationWarning>
      <body>
        
        <ClientLayout>{children}</ClientLayout> {/* Wrap children with ClientLayout */}
      </body>
    </html>
    </ClerkProvider>
  );
}
